(() => {
const KEY="tt_pixel_art_maker_v1",canvas=document.getElementById("pixelCanvas"),ctx=canvas.getContext("2d");
const $=id=>document.getElementById(id);
const state={size:16,pixels:[],color:PIXEL_PALETTE[0],tool:"draw",mirror:false,history:[],future:[],underlay:null,underlayVisible:false,underlayOpacity:.35,underlayUrl:null,underlayScale:1,underlayX:0,underlayY:0,underlayLocked:false};
const blank=()=>Array(state.size*state.size).fill(null);
function resize(){const s=Math.max(160,Math.floor(Math.min(canvas.parentElement.clientWidth-12,canvas.parentElement.clientHeight-12)));canvas.width=s;canvas.height=s;draw()}
function draw(){const n=state.size,s=canvas.width/n;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);
if(state.underlay&&state.underlayVisible){ctx.save();ctx.globalAlpha=state.underlayOpacity;const iw=state.underlay.naturalWidth,ih=state.underlay.naturalHeight,base=Math.max(canvas.width/iw,canvas.height/ih),scale=base*state.underlayScale,dw=iw*scale,dh=ih*scale;ctx.drawImage(state.underlay,(canvas.width-dw)/2+state.underlayX*canvas.width/100,(canvas.height-dh)/2+state.underlayY*canvas.height/100,dw,dh);ctx.restore()}
state.pixels.forEach((c,i)=>{if(c){ctx.fillStyle=c;ctx.fillRect((i%n)*s,Math.floor(i/n)*s,s,s)}});ctx.strokeStyle="rgba(71,85,105,.28)";for(let i=0;i<=n;i++){const p=Math.round(i*s)+.5;ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(canvas.width,p);ctx.stroke()}}
function point(e){const r=canvas.getBoundingClientRect(),n=state.size;return{x:Math.max(0,Math.min(n-1,Math.floor((e.clientX-r.left)/r.width*n))),y:Math.max(0,Math.min(n-1,Math.floor((e.clientY-r.top)/r.height*n)))}} 
function history(){state.history.push(state.pixels.slice());if(state.history.length>40)state.history.shift();state.future=[]}
function fill(x,y){const n=state.size,target=state.pixels[y*n+x]||null;if(target===state.color)return;const q=[[x,y]],seen=new Set();while(q.length){const [a,b]=q.pop();if(a<0||b<0||a>=n||b>=n)continue;const k=b*n+a;if(seen.has(k)||((state.pixels[k]||null)!==target))continue;seen.add(k);state.pixels[k]=state.color;q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}}
function paint(x,y,record=true){const n=state.size;if(record)history();if(state.tool==="fill"){fill(x,y)}else if(state.tool==="picker"){const c=state.pixels[y*n+x];if(c){state.color=c;$("colorInput").value=c;palette();$("statusText").textContent="色をひろいました。"}else if(state.underlay&&state.underlayVisible){const r=canvas.getBoundingClientRect(),px=Math.floor((x+.5)*canvas.width/n),py=Math.floor((y+.5)*canvas.height/n),sample=ctx.getImageData(px,py,1,1).data;state.color="#"+[sample[0],sample[1],sample[2]].map(v=>v.toString(16).padStart(2,"0")).join("");$("colorInput").value=state.color;palette();$("statusText").textContent="下絵から色をひろいました。"}state.tool="draw";tools();return}else{const c=state.tool==="erase"?null:state.color;state.pixels[y*n+x]=c;if(state.mirror)state.pixels[y*n+(n-1-x)]=c}draw()}
function palette(){const p=$("palette");p.innerHTML="";PIXEL_PALETTE.forEach(c=>{const b=document.createElement("button");b.className="color-btn"+(c===state.color?" active":"");b.style.background=c;b.setAttribute("aria-label",c);b.onclick=()=>{state.color=c;state.tool="draw";palette();tools()};p.appendChild(b)})}
function tools(){document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===state.tool))}
function updateSizeUI(){$("sizeLabel").textContent=state.size+"×"+state.size;$("cellCount").textContent=(state.size*state.size)+"マス";$("decreaseSizeBtn").disabled=state.size<=16;$("increaseSizeBtn").disabled=state.size>=64}
function changeSize(next){next=Math.max(16,Math.min(64,next));if(next===state.size)return;const old=state.size,oldPixels=state.pixels.slice();history();const p=blank(),offset=Math.floor((next-old)/2);for(let y=0;y<old;y++)for(let x=0;x<old;x++){const v=oldPixels[y*old+x];const nx=x+offset,ny=y+offset;if(v&&nx>=0&&ny>=0&&nx<next&&ny<next)p[ny*next+nx]=v}state.size=next;state.pixels=p;updateSizeUI();resize()}
function works(){const a=JSON.parse(localStorage.getItem(KEY)||"[]"),el=$("worksList");el.innerHTML="";if(!a.length){el.innerHTML='<div class="empty">まだ作品がありません。まず1枚つくってみよう。</div>';return}a.forEach(w=>{const card=document.createElement("article");card.className="work-card";const c=document.createElement("canvas");c.width=c.height=256;const x=c.getContext("2d"),s=256/w.size;x.fillStyle="#fff";x.fillRect(0,0,256,256);w.pixels.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%w.size*s,Math.floor(i/w.size)*s,s,s)}});const strong=document.createElement("strong");strong.textContent=w.title;const sm=document.createElement("small");sm.textContent=w.size+"×"+w.size;card.append(c,strong,sm);el.appendChild(card)})}
function start(){state.size=16;state.pixels=blank();state.history=[];state.future=[];state.tool="draw";$("editorPanel").classList.remove("hidden");$("worksPanel").classList.add("hidden");$("guideText").textContent="16×16から始めて、＋ボタンでマスを増やせます。";$("workTitle").value="";updateSizeUI();resize();tools();$("statusText").textContent=""}
let drawing=false;
canvas.addEventListener("pointerdown",e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing=true;history();const p=point(e);paint(p.x,p.y,false)});
canvas.addEventListener("pointermove",e=>{if(drawing&&e.buttons===1&&(state.tool==="draw"||state.tool==="erase")){const p=point(e);paint(p.x,p.y,false)}});
canvas.addEventListener("pointerup",()=>drawing=false);canvas.addEventListener("pointercancel",()=>drawing=false);
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;tools()});
$("mirrorBtn").onclick=()=>{const n=state.size;history();const p=blank();for(let y=0;y<n;y++)for(let x=0;x<n;x++)p[y*n+(n-1-x)]=state.pixels[y*n+x];state.pixels=p;draw();$("statusText").textContent="左右反転しました。"};
$("increaseSizeBtn").onclick=()=>changeSize(state.size+8);
$("decreaseSizeBtn").onclick=()=>changeSize(state.size-8);
$("undoBtn").onclick=()=>{if(state.history.length){state.future.push(state.pixels.slice());state.pixels=state.history.pop();draw()}};
$("redoBtn").onclick=()=>{if(state.future.length){state.history.push(state.pixels.slice());state.pixels=state.future.pop();draw()}};
$("colorInput").oninput=e=>{state.color=e.target.value;state.tool="draw";palette();tools()};
$("underlayInput").onchange=e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(state.underlayUrl)URL.revokeObjectURL(state.underlayUrl);state.underlayUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{state.underlay=img;state.underlayVisible=true;state.underlayScale=1;state.underlayX=0;state.underlayY=0;state.underlayLocked=false;$("underlayScale").value=1;$("underlayX").value=0;$("underlayY").value=0;$("underlayScaleLabel").textContent="100%";$("underlayXLabel").textContent="0%";$("underlayYLabel").textContent="0%";$("underlayLockBtn").textContent="下絵を固定";$("underlayToggleBtn").textContent="下絵を非表示";draw();$("statusText").textContent="写真を下絵にしました。"};img.src=state.underlayUrl};
$("underlayToggleBtn").onclick=()=>{if(!state.underlay)return;state.underlayVisible=!state.underlayVisible;$("underlayToggleBtn").textContent=state.underlayVisible?"下絵を非表示":"下絵を表示";draw()};
$("underlayClearBtn").onclick=()=>{if(state.underlayUrl)URL.revokeObjectURL(state.underlayUrl);state.underlay=null;state.underlayUrl=null;state.underlayVisible=false;$("underlayInput").value="";$("underlayToggleBtn").textContent="下絵を表示";draw();$("statusText").textContent="下絵を消しました。"};
$("underlayOpacity").oninput=e=>{state.underlayOpacity=Number(e.target.value);$("underlayOpacityLabel").textContent=Math.round(state.underlayOpacity*100)+"%";draw()};
const updateUnderlayScale=e=>{if(state.underlayLocked)return;const v=Math.max(.5,Math.min(2.5,Number(e.target.value)||1));state.underlayScale=v;e.target.value=v;$("underlayScaleLabel").textContent=Math.round(v*100)+"%";draw()};$("underlayScale").oninput=updateUnderlayScale;$("underlayScale").onchange=updateUnderlayScale;
$("underlayX").oninput=e=>{if(state.underlayLocked)return;state.underlayX=Math.max(-100,Math.min(100,Number(e.target.value)||0));$("underlayXLabel").textContent=Math.round(state.underlayX)+"%";draw()};
$("underlayY").oninput=e=>{if(state.underlayLocked)return;state.underlayY=Math.max(-100,Math.min(100,Number(e.target.value)||0));$("underlayYLabel").textContent=Math.round(state.underlayY)+"%";draw()};
$("underlayLockBtn").onclick=()=>{if(!state.underlay)return;state.underlayLocked=!state.underlayLocked;["underlayScale","underlayX","underlayY"].forEach(id=>$(id).disabled=state.underlayLocked);$("underlayLockBtn").textContent=state.underlayLocked?"下絵の固定を解除":"下絵を固定"};
$("scrollLockBtn").onclick=()=>{document.body.classList.toggle("scroll-locked");const locked=document.body.classList.contains("scroll-locked");$("scrollLockBtn").textContent=locked?"スクロールロック中":"スクロールロック"};
$("saveBtn").onclick=()=>{const a=JSON.parse(localStorage.getItem(KEY)||"[]");a.unshift({id:Date.now(),title:$("workTitle").value.trim()||"わたしのピクセルアート",size:state.size,pixels:state.pixels.slice()});localStorage.setItem(KEY,JSON.stringify(a.slice(0,30)));$("statusText").textContent="作品をこの端末に保存しました。";works()};
$("pngBtn").onclick=()=>{const out=document.createElement("canvas"),scale=Math.max(8,Math.floor(512/state.size));out.width=out.height=state.size*scale;const x=out.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,out.width,out.height);state.pixels.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%state.size*scale,Math.floor(i/state.size)*scale,scale,scale)}});const a=document.createElement("a");a.download=($("workTitle").value.trim()||"pixel-art")+".png";a.href=out.toDataURL("image/png");a.click();$("statusText").textContent="PNGを書き出しました。"};
$("newBtn").onclick=start;
document.querySelectorAll(".mode-tab").forEach(b=>b.onclick=()=>{const m=b.dataset.mode;if(m==="free"){start()}else{$("editorPanel").classList.add("hidden");$("worksPanel").classList.remove("hidden");works()}document.querySelectorAll(".mode-tab").forEach(t=>t.classList.toggle("active",t===b))});
document.addEventListener("touchmove",e=>{if(document.body.classList.contains("scroll-locked")&&!e.target.closest(".underlay-options"))e.preventDefault()},{passive:false});palette();start();
})();