(() => {
const KEY="tt_pixel_art_maker_v1",canvas=document.getElementById("pixelCanvas"),ctx=canvas.getContext("2d");
const state={size:16,pixels:[],color:PIXEL_PALETTE[0],tool:"draw",mirror:false,example:null,history:[],future:[],filter:"すべて"};
const $=id=>document.getElementById(id),blank=()=>Array(state.size*state.size).fill(null);
const colorMap=["#fff","#111827","#3b82f6","#ef4444"];
function exPixels(ex){return ex.pixels.flatMap(r=>[...r].map(n=>n==="0"?null:(colorMap[+n]||"#ef4444")))}
function resize(){const s=Math.max(160,Math.floor(Math.min(canvas.parentElement.clientWidth-12,canvas.parentElement.clientHeight-12)));canvas.width=s;canvas.height=s;draw()}
function draw(){const n=state.size,s=canvas.width/n;ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);state.pixels.forEach((c,i)=>{if(c){ctx.fillStyle=c;ctx.fillRect((i%n)*s,Math.floor(i/n)*s,s,s)}});ctx.strokeStyle="rgba(71,85,105,.28)";ctx.lineWidth=1;for(let i=0;i<=n;i++){let p=Math.round(i*s)+.5;ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(canvas.width,p);ctx.stroke()}}
function point(e){const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(15,Math.floor((e.clientX-r.left)/r.width*16))),y:Math.max(0,Math.min(15,Math.floor((e.clientY-r.top)/r.height*16)))}} 
function history(){state.history.push(state.pixels.slice());if(state.history.length>40)state.history.shift();state.future=[]}
function fill(x,y){const target=state.pixels[y*16+x]||null;if(target===state.color)return;const q=[[x,y]],seen=new Set();while(q.length){const [a,b]=q.pop();if(a<0||b<0||a>=16||b>=16)continue;const k=b*16+a;if(seen.has(k)||((state.pixels[k]||null)!==target))continue;seen.add(k);state.pixels[k]=state.color;q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}}
function paint(x,y){if(state.tool==="picker"){const c=state.pixels[y*16+x];if(c){state.color=c;palette();}state.tool="draw";tools();return}history();if(state.tool==="fill")fill(x,y);else{const c=state.tool==="erase"?null:state.color;state.pixels[y*16+x]=c;if(state.mirror)state.pixels[y*16+(15-x)]=c}draw()}
function palette(){const p=$("palette");p.innerHTML="";PIXEL_PALETTE.forEach(c=>{const b=document.createElement("button");b.className="color-btn"+(c===state.color?" active":"");b.style.background=c;b.setAttribute("aria-label",c);b.onclick=()=>{state.color=c;state.tool="draw";palette();tools()};p.appendChild(b)})}
function tools(){document.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===state.tool));$("mirrorBtn").classList.toggle("active",state.mirror)}
function small(c,ex){const x=c.getContext("2d"),p=exPixels(ex),s=256/16;x.fillStyle="#fff";x.fillRect(0,0,256,256);p.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%16*s,Math.floor(i/16)*s,s,s)}})}
function renderExamples(){const cats=["すべて",...new Set(PIXEL_EXAMPLES.map(x=>x.category))];$("categoryFilters").innerHTML="";cats.forEach(cat=>{const b=document.createElement("button");b.className="filter"+(state.filter===cat?" active":"");b.textContent=cat;b.onclick=()=>{state.filter=cat;renderExamples()};$("categoryFilters").appendChild(b)});$("exampleList").innerHTML="";PIXEL_EXAMPLES.filter(x=>state.filter==="すべて"||x.category===state.filter).forEach(ex=>{const b=document.createElement("button");b.className="example-card";const c=document.createElement("canvas");c.className="example-thumb";c.width=c.height=256;small(c,ex);b.append(c);const strong=document.createElement("strong");strong.textContent=ex.title;const span=document.createElement("span");span.textContent=ex.category+" ・ 16×16";b.append(strong,span);b.onclick=()=>start(ex);$("exampleList").appendChild(b)})}
function reference(ex){$("referenceCanvasWrap").innerHTML="";if(!ex){$("referenceTitle").textContent="自由につくる";$("referenceSize").textContent="16×16";return}const c=document.createElement("canvas");c.width=c.height=320;small320(c,ex);$("referenceCanvasWrap").appendChild(c);$("referenceTitle").textContent=ex.title;$("referenceSize").textContent="16×16"}
function small320(c,ex){const x=c.getContext("2d"),p=exPixels(ex),s=20;x.fillStyle="#fff";x.fillRect(0,0,320,320);p.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%16*s,Math.floor(i/16)*s,s,s)}})}
function start(ex){state.example=ex;state.pixels=ex?exPixels(ex):blank();state.history=[];state.future=[];state.tool="draw";$("examplePanel").classList.add("hidden");$("editorPanel").classList.remove("hidden");$("worksPanel").classList.add("hidden");$("guideText").textContent=ex?"お手本を見ながら、1マスずつつくってみよう。":"好きな色で自由につくってみよう。";$("workTitle").value="";reference(ex);resize();tools();$("statusText").textContent=""}
function works(){const a=JSON.parse(localStorage.getItem(KEY)||"[]"),el=$("worksList");el.innerHTML="";if(!a.length){el.innerHTML='<div class="empty">まだ作品がありません。まず1枚つくってみよう。</div>';return}a.forEach(w=>{const card=document.createElement("article");card.className="work-card";const c=document.createElement("canvas");c.width=c.height=256;const x=c.getContext("2d"),s=256/w.size;x.fillStyle="#fff";x.fillRect(0,0,256,256);w.pixels.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%w.size*s,Math.floor(i/w.size)*s,s,s)}});const strong=document.createElement("strong");strong.textContent=w.title;const sm=document.createElement("small");sm.textContent=w.size+"×"+w.size;card.append(c,strong,sm);el.appendChild(card)})}
canvas.addEventListener("pointerdown",e=>{e.preventDefault();canvas.setPointerCapture(e.pointerId);const p=point(e);paint(p.x,p.y)});
canvas.addEventListener("pointermove",e=>{if(e.buttons===1&&(state.tool==="draw"||state.tool==="erase")){const p=point(e);paint(p.x,p.y)}});
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;tools()});
$("mirrorBtn").onclick=()=>{state.mirror=!state.mirror;tools()};
$("undoBtn").onclick=()=>{if(state.history.length){state.future.push(state.pixels.slice());state.pixels=state.history.pop();draw()}};
$("redoBtn").onclick=()=>{if(state.future.length){state.history.push(state.pixels.slice());state.pixels=state.future.pop();draw()}};
$("colorInput").oninput=e=>{state.color=e.target.value;state.tool="draw";palette();tools()};
$("hideReferenceBtn").onclick=()=>{const w=$("referenceCanvasWrap"),hide=!w.classList.contains("hidden");w.classList.toggle("hidden",hide);$("hideReferenceBtn").textContent=hide?"お手本を表示":"お手本を隠す"};
$("saveBtn").onclick=()=>{const a=JSON.parse(localStorage.getItem(KEY)||"[]");a.unshift({id:Date.now(),title:$("workTitle").value.trim()||"わたしのピクセルアート",size:16,pixels:state.pixels.slice()});localStorage.setItem(KEY,JSON.stringify(a.slice(0,30)));$("statusText").textContent="作品をこの端末に保存しました。";works()};
$("pngBtn").onclick=()=>{const out=document.createElement("canvas"),scale=32;out.width=out.height=16*scale;const x=out.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,out.width,out.height);state.pixels.forEach((v,i)=>{if(v){x.fillStyle=v;x.fillRect(i%16*scale,Math.floor(i/16)*scale,scale,scale)}});const a=document.createElement("a");a.download=($("workTitle").value.trim()||"pixel-art")+".png";a.href=out.toDataURL("image/png");a.click();$("statusText").textContent="PNGを書き出しました。"};
$("newBtn").onclick=()=>{state.example=null;$("editorPanel").classList.add("hidden");$("examplePanel").classList.remove("hidden")};
document.querySelectorAll(".mode-tab").forEach(b=>b.onclick=()=>{const m=b.dataset.mode;if(m==="example"){$("editorPanel").classList.add("hidden");$("worksPanel").classList.add("hidden");$("examplePanel").classList.remove("hidden")}else if(m==="free"){start(null)}else{$("examplePanel").classList.add("hidden");$("editorPanel").classList.add("hidden");$("worksPanel").classList.remove("hidden");works()}document.querySelectorAll(".mode-tab").forEach(t=>t.classList.toggle("active",t===b))});
window.addEventListener("resize",resize);palette();renderExamples();works();
})();